[versions]
springBoot = "3.3.4"
kotlin = "2.0.20"
kotlinSpring = "2.0.20"
springDependencyManagement = "1.1.6"

[plugins]
springBootPlugin = { id = "org.springframework.boot", version.ref="springBoot"}
kotlinPlugin = {id = "org.jetbrains.kotlin.jvm", version.ref="kotlin"}
springDependencyManagementPlugin = {id="io.spring.dependency-management", version.ref="springDependencyManagement"}
kotlinSpringPlugin = {id = "org.jetbrains.kotlin.plugin.spring", version.ref="kotlinSpring"}